# site settings
title: samilawson.github.io
subtitle: Sam Lawson
email: samilawson17@gmail.com
description: Personal site for nothing in particular.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Nunya
city: Memphis
state: TN
zip_code: Also Nunya
country: United States of America
phone: Additionally nunya

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/Sam_Lawson_17

# build settings
markdown: kramdown

sass:
  style: compressed
